
## working directory (this is where the Snakefile exists)
baseDir: "/cfs/klemming/projects/snic/naiss2024-22-1277/Dania/GitHub/isoforms_project/processOnDardel/"

## raw data dir (contains fastq files and the inclusive list. Each plate is a separate folder)
# path to the folder which contains the raw data of the project
originalRawDataDir: "/cfs/klemming/projects/snic/naiss2024-22-1277/DATA/"
# name of folder which will be created int eh working directory, containing symlinks to the fastq files
rawDataDir: "raw/"

## reference genome
starRefGenome: "/cfs/klemming/projects/snic/naiss2024-22-1277/Dania/Db/mouse/gencode/release_M37/refSTAR/refSTAR-2.7.11b-primaryRef-fullAnnotation-overhang133/ref"

## tools
umi_tools: "/cfs/klemming/projects/snic/naiss2024-22-1277/Dania/Apps/pixiEnvs/umi_tools/umi_tools-1.1.6/.pixi/envs/default/bin/umi_tools"
cutadaptMod: "cutadapt/5.1"
starMod: "rnastar/2.7.11b"
samtoolsMod: "samtools/1.20"

