#
# Date (created): April 16, 2026
# Author: Dania Machlab
# Overview: 
# 	This Snakefile contains all analyses and scripts run on Dardel, starting from 
# 	the raw fastq files, all the way to the final count matrices. We are dealing with
# 	smartSeq3 data. This means that some R1 reads (those fromt he 5' end of the 
#	original mRNA) contain a tag sequence which is followed by an 8-base long 
#	unique molecular identifier (UMI). Other R1 reads (internal reads from the 
# 	transcript) contain no tag or UMI sequences. All R2 reads also just contain the 
# 	transcript sequence. TODO: provide more details on the setup, read lengths, 
# 	why some were trimmed by NGI, that they gave us the full untrimmed versions 
#	for a subset of the plates, the metadata from the group, expected adapters etc.
# Running Snakemake:
# 	# to run snakemake on Dardel, start by activating the python venv
# 	venv="/cfs/klemming/home/d/dama4465/Projects/M_Szczot_2405/naiss2024-22-1277/Dania/Apps/snakemake/snakemake-v9.19.0/bin"
# 	source $venv/activate
#
#	# dry run (note that the profile/config.yaml file cotnains parameter specifically for submitting on Dardel and to this project)
#       snakemake -j 2 --profile slurm -np
#
#

## config file 
## ... This file specifies the tools and references used
configfile: "config.yaml"

## globals
import os

baseDir = config["baseDir"]
originalRawDataDir = config["originalRawDataDir"]
rawDataDir = config["rawDataDir"]; os.makedirs(rawDataDir, exist_ok=True)

umi_tools = config["umi_tools"]
cutadaptMod = config["cutadaptMod"]
starMod = config["starMod"]
samtoolsMod = config["samtoolsMod"]

starRefGenome = config["starRefGenome"]

## plates (hard-coded so we can easily include/exclude specific plates)
#plates = ['sample_01', 'sample_02', 'sample_03', 'sample_04', 'sample_05', 
#          'sample_06', 'sample_07', 'sample_08', 'sample_09', 'sample_10', 
#          'sample_11']
plates = ['sample_01']

## create a dictionary, with plates as keys, storing ngiID and the inclusion
## ... file as values.
plateInfo = {
  plate: {
    "ngiID": [f for f in os.listdir(os.path.join(originalRawDataDir, plate, "raw")) if "_R1_" in f][0].split("_R1_")[0],
    "inclusionListFile": [f for f in os.listdir(os.path.join(originalRawDataDir, plate, "raw")) if "well_barcodes" in f][0]
  }
  for plate in plates
}

print("Processing the following plates: ", plates)
print("With the following plate information: ", plateInfo)

## ------------------------------------------------------------------------
## 00 - default rules to run
## ------------------------------------------------------------------------

rule all:
  input:
    ## 01: make symlinks to raw data
    expand(rawDataDir + "{plate}/{ngiID}_R1_001.fastq.gz", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand(rawDataDir + "{plate}/{ngiID}_R2_001.fastq.gz", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("logs/ruleLogs/makeSymLinks/{plate}_{ngiID}.log", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    ## 02: process fastq files before mapping
    expand("logs/ruleLogs/extractUMIs/{plate}_{ngiID}.log", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("logs/ruleLogs/trimAdapter/{plate}/{ngiID}_cutadapt.report.txt", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("processed/fastqs/{plate}/{ngiID}_R1_001.extractedUmi.trimmed.fixedReadName.fastq.gz", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("processed/fastqs/{plate}/{ngiID}_R2_001.extractedUmi.trimmed.fixedReadName.fastq.gz", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("logs/ruleLogs/fixReadNames/{plate}/{ngiID}_fixReadNames.log", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    ## 03: map with STAR
    expand("processed/bam/{plate}/{ngiID}_Aligned.sortedByCoord.out.bam", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("processed/bam/{plate}/{ngiID}_Aligned.sortedByCoord.out.bam.bai", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("logs/ruleLogs/mapWithStar/{plate}/{ngiID}_mapWithStar.log", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),

## ------------------------------------------------------------------------
## 01 - make symbolic links to raw data 
## ------------------------------------------------------------------------

rule makeSymLinks:
  input:
    inR1 = originalRawDataDir + "{plate}/raw/{ngiID}_R1_001.fastq.gz",
    inR2 = originalRawDataDir + "{plate}/raw/{ngiID}_R2_001.fastq.gz"
  output:
    outR1 = rawDataDir + "{plate}/{ngiID}_R1_001.fastq.gz",
    outR2 = rawDataDir + "{plate}/{ngiID}_R2_001.fastq.gz",
    logFile = "logs/ruleLogs/makeSymLinks/{plate}_{ngiID}.log"
  params:  
    outDir = directory(rawDataDir + "{plate}")
  shell:
    '''
    # setup 
    cd {baseDir} && \
    if [ ! -d "logs/ruleLogs/makeSymLinks" ]; then
      mkdir -p "logs/ruleLogs/makeSymLinks";
    fi && \
    if [ ! -d {params.outDir} ]; then
      mkdir -p {params.outDir};
    fi && \
 
    # create symbolic links to fastq files
    echo "ln -sf {input.inR1} {output.outR1}" > {output.logFile} && \
    ln -sf {input.inR1} {output.outR1} >> {output.logFile} 2>&1 && \
    echo "ln -sf {input.inR2} {output.outR2}" >> {output.logFile} && \
    ln -sf {input.inR2} {output.outR2} >> {output.logFile} 2>&1
    '''

## ------------------------------------------------------------------------
## 02 - process fastq files before mapping
##        this involves: extracting the UMI if present, trimming adapters
##        and fixing the read names before mapping. 
## ------------------------------------------------------------------------

rule extractUMIs:
  input:
    inR1 = rawDataDir + "{plate}/{ngiID}_R1_001.fastq.gz",
    inR2 = rawDataDir + "{plate}/{ngiID}_R2_001.fastq.gz"
  output:
    outUmiR1 = temp("processed/fastqs/{plate}/{ngiID}_R1_001.umi.fastq.gz"),
    outNoUmiR1 = temp("processed/fastqs/{plate}/{ngiID}_R1_001.noUmi.fastq.gz"),
    outUmiR2 = temp("processed/fastqs/{plate}/{ngiID}_R2_001.umi.fastq.gz"),
    outNoUmiR2 = temp("processed/fastqs/{plate}/{ngiID}_R2_001.noUmi.fastq.gz"),    
    logFile = "logs/ruleLogs/extractUMIs/{plate}_{ngiID}.log"
  params:
    fastqDir = directory("processed/fastqs/{plate}"),
    bcPatternParam = lambda wildcards: """--bc-pattern='^(?P<discard_1>ATTGCGCAATG{s<=1})(?P<umi_1>.{8}).*'"""
  shell:
    '''
    # setup
    cd {baseDir} && \
    if [ ! -d "logs/ruleLogs/extractUMIs" ]; then
      mkdir -p "logs/ruleLogs/extractUMIs";
    fi && \
    if [ ! -d {params.fastqDir} ]; then
      mkdir -p {params.fastqDir};
    fi && \
    
    # extract UMI if present. Some R1 reads contain UMIs. These are the reads
    # ... which happened to be at the strat of the original transcript (5' end). 
    # ... If an R1 read starts with a specific tag sequence (ATTGCGCAATG), then 
    # ... this is followed by 8 bases corresponding to the UMI. 
    {umi_tools} extract --extract-method=regex --stdin={input.inR1} --read2-in={input.inR2} \
      --stdout={output.outUmiR1} --read2-out={output.outUmiR2} {params.bcPatternParam} \
      --log={output.logFile} --filtered-out={output.outNoUmiR1} --filtered-out2={output.outNoUmiR2}
    '''

rule concatenateFastqs:
  input:
    inUmiR1 = "processed/fastqs/{plate}/{ngiID}_R1_001.umi.fastq.gz",
    inNoUmiR1 = "processed/fastqs/{plate}/{ngiID}_R1_001.noUmi.fastq.gz",
    inUmiR2 = "processed/fastqs/{plate}/{ngiID}_R2_001.umi.fastq.gz",
    inNoUmiR2 = "processed/fastqs/{plate}/{ngiID}_R2_001.noUmi.fastq.gz"
  output:
    outR1 = temp("processed/fastqs/{plate}/{ngiID}_R1_001.umi.noUmi.concat.fastq.gz"),
    outR2 = temp("processed/fastqs/{plate}/{ngiID}_R2_001.umi.noUmi.concat.fastq.gz"),
    logFile = "logs/ruleLogs/concatenateFastqs/{plate}_{ngiID}.log"
  shell:
    '''
    # setup
    cd {baseDir} && \
    
    # concatenate
    echo "cat {input.inUmiR1} {input.inNoUmiR1} > {output.outR1}" > {output.logFile} && \
    cat {input.inUmiR1} {input.inNoUmiR1} > {output.outR1} 2>> {output.logFile} && \
    echo "cat {input.inUmiR2} {input.inNoUmiR2} > {output.outR2}" >> {output.logFile} && \
    cat {input.inUmiR2} {input.inNoUmiR2} > {output.outR2} 2>> {output.logFile}
    '''

rule trimAdapter:
  input:
    inR1 = "processed/fastqs/{plate}/{ngiID}_R1_001.umi.noUmi.concat.fastq.gz",
    inR2 = "processed/fastqs/{plate}/{ngiID}_R2_001.umi.noUmi.concat.fastq.gz"
  output:
    outR1 = temp("processed/fastqs/{plate}/{ngiID}_R1_001.extractedUmi.trimmed.fastq.gz"),
    outR2 = temp("processed/fastqs/{plate}/{ngiID}_R2_001.extractedUmi.trimmed.fastq.gz"), 
    cutadaptReport = "logs/ruleLogs/trimAdapter/{plate}/{ngiID}_cutadapt.report.txt"
  shell:
    '''
    # setup
    cd {baseDir} && \
    module load {cutadaptMod} && \

    # trim adapter sequence
    # ... we trim for the expected Tn5 adapter sequence (CTGTCTCTTATACACATCT) from the 3' ends of R1 and R2
    # ... we also trim for cases where R2 has read into an R1 which contains the tag and UMI. In 
    # ... this case, we need to trim for revCompUMI.revCompTag.adapter.
    cutadapt -a CTGTCTCTTATACACATCT -A N{{8}}CATTGCGCAATCTGTCTCTTATACACATCT -A CTGTCTCTTATACACATCT \
      --cores 0 --minimum-length 10 --pair-filter=any -o {output.outR1} -p {output.outR2} \
      {input.inR1} {input.inR2} > {output.cutadaptReport} 2>&1
    '''

rule fixReadNames:
  input:
    inR1 = "processed/fastqs/{plate}/{ngiID}_R1_001.extractedUmi.trimmed.fastq.gz",
    inR2 = "processed/fastqs/{plate}/{ngiID}_R2_001.extractedUmi.trimmed.fastq.gz",
    script = "scripts/fixFastqReadNames.py"
  output:
    outR1 = "processed/fastqs/{plate}/{ngiID}_R1_001.extractedUmi.trimmed.fixedReadName.fastq.gz",
    outR2 = "processed/fastqs/{plate}/{ngiID}_R2_001.extractedUmi.trimmed.fixedReadName.fastq.gz",
    logFile = "logs/ruleLogs/fixReadNames/{plate}/{ngiID}_fixReadNames.log"
  params:
    threads = 10
  shell:
    '''
    # setup
    cd {baseDir} && \
    
    python3 {input.script} --inFastq1 {input.inR1} --inFastq2 {input.inR2} --outFastq1 {output.outR1} \
      --outFastq2 {output.outR2} --threads {params.threads} > {output.logFile} 2>&1
    '''

## ------------------------------------------------------------------------
## 03 - map reads (per plate) with STAR
## ------------------------------------------------------------------------

rule mapWithStar:
  input:
    R1 = "processed/fastqs/{plate}/{ngiID}_R1_001.extractedUmi.trimmed.fixedReadName.fastq.gz",
    R2 = "processed/fastqs/{plate}/{ngiID}_R2_001.extractedUmi.trimmed.fixedReadName.fastq.gz"
  output:
    bam = "processed/bam/{plate}/{ngiID}_Aligned.sortedByCoord.out.bam", 
    index = "processed/bam/{plate}/{ngiID}_Aligned.sortedByCoord.out.bam.bai",
    logFile = "logs/ruleLogs/mapWithStar/{plate}/{ngiID}_mapWithStar.log"
  params:
    threads = 30, 
    prefix = "processed/bam/{plate}/{ngiID}_"
  shell:
    '''
    # setup
    cd {baseDir} && \
    module load {starMod} && \
    module load {samtoolsMod} && \

    # map (keeping unmapped read in the bam file)
    STAR --runThreadN {params.threads} --runMode alignReads --genomeDir {starRefGenome} \
      --readFilesIn {input.R1} {input.R2} --outFilterType BySJout --outFilterMultimapNmax 20 \
      --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 \
      --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 \
      --alignMatesGapMax 1000000 --outFileNamePrefix {params.prefix} --outSAMtype BAM SortedByCoordinate \
      --outSAMattributes NH HI AS nM XS --outSAMunmapped Within --readFilesCommand zcat > {output.logFile} 2>&1 && \
 
    # index
    samtools index {output.bam}
    '''


