#
# Date (created): April 16, 2026
# Author: Dania Machlab
# Overview: 
# 	This Snakefile contains all analyses and scripts run on Dardel, starting from 
# 	the raw fastq files, all the way to the final count matrices. We are dealing with
# 	smartSeq3 data. This means that some R1 reads (those fromt he 5' end of the 
#	original mRNA) contain a tag sequence which is followed by an 8-base long 
#	unique molecular identifier (UMI). Other R1 reads (internal reads from the 
# 	transcript) contain no tag or UMI sequences. All R2 reads also just contain the 
# 	transcript sequence. TODO: provide more details on the setup, read lengths, 
# 	why some were trimmed by NGI, that they gave us the full untrimmed versions 
#	for a subset of the plates, the metadata from the group, expected adapters etc.
# Running Snakemake:
# 	# to run snakemake on Dardel, start by activating the python venv
# 	venv="/cfs/klemming/home/d/dama4465/Projects/M_Szczot_2405/naiss2024-22-1277/Dania/Apps/snakemake/snakemake-v9.19.0/bin"
# 	source $venv/activate
#
#	# dry run (note that the profile/config.yaml file cotnains parameter specifically for submitting on Dardel and to this project)
#       snakemake -j 2 --profile slurm -np
#
#

## config file 
## ... This file specifies the tools and references used
configfile: "config.yaml"

## globals
import os

baseDir = config["baseDir"]
originalRawDataDir = config["originalRawDataDir"]
rawDataDir = config["rawDataDir"]; os.makedirs(rawDataDir, exist_ok=True)

## plates (hard-coded so we can easily include/exclude specific plates)
plates = ['sample_01', 'sample_02', 'sample_03', 'sample_04', 'sample_05', 
          'sample_06', 'sample_07', 'sample_08', 'sample_09', 'sample_10', 
          'sample_11']

## create a dictionary, with plates as keys, storing ngiID and the inclusion
## ... file as values.
plateInfo = {
  plate: {
    "ngiID": [f for f in os.listdir(os.path.join(originalRawDataDir, plate, "raw")) if "_R1_" in f][0].split("_R1_")[0],
    "inclusionListFile": [f for f in os.listdir(os.path.join(originalRawDataDir, plate, "raw")) if "well_barcodes" in f][0]
  }
  for plate in plates
}

print("Processing the following plates: ", plates)
print("With the following plate information: ", plateInfo)

## ------------------------------------------------------------------------
## 00 - default rules to run
## ------------------------------------------------------------------------

rule all:
  input:
    ## 01: make symlinks to raw data
    expand(rawDataDir + "{plate}/{ngiID}_R1_001.fastq.gz", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand(rawDataDir + "{plate}/{ngiID}_R2_001.fastq.gz", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),
    expand("logs/ruleLogs/makeSymLinks/{plate}_{ngiID}.log", zip, plate = plates, ngiID = [plateInfo[p]['ngiID'] for p in plates]),



## ------------------------------------------------------------------------
## 01 - make symbolic links to raw data 
## ------------------------------------------------------------------------

rule makeSymLinks:
  input:
    inR1 = originalRawDataDir + "{plate}/raw/{ngiID}_R1_001.fastq.gz",
    inR2 = originalRawDataDir + "{plate}/raw/{ngiID}_R2_001.fastq.gz"
  output:
    outR1 = rawDataDir + "{plate}/{ngiID}_R1_001.fastq.gz",
    outR2 = rawDataDir + "{plate}/{ngiID}_R2_001.fastq.gz",
    logFile = "logs/ruleLogs/makeSymLinks/{plate}_{ngiID}.log"
  params:  
    outDir = directory(rawDataDir + "{plate}")
  shell:
    '''
    # setup 
    cd {baseDir} && \
    if [ ! -d "logs/ruleLogs/makeSymLinks" ]; then
      mkdir -p "logs/ruleLogs/makeSymLinks";
    fi && \
    if [ ! -d {params.outDir} ]; then
      mkdir -p {params.outDir};
    fi && \
 
    # create symbolic links to fastq files
    echo "ln -sf {input.inR1} {output.outR1}" > {output.logFile} && \
    ln -sf {input.inR1} {output.outR1} >> {output.logFile} 2>&1 && \
    echo "ln -sf {input.inR2} {output.outR2}" >> {output.logFile} && \
    ln -sf {input.inR2} {output.outR2} >> {output.logFile} 2>&1
    '''

